<?php
http_response_code(200);
header('Content-Type: application/json');

$data = [
    'is_employee' => false,
    'is_friend' => false,
    'subreddit' => [
        'default_set' => true,
        'user_is_contributor' => false,
        'banner_img' => '',
        'restrict_posting' => true,
        'user_is_banned' => false,
        'free_form_reports' => true,
        'community_icon' => null,
        'show_media' => true,
        'icon_color' => '#FF4500',
        'user_is_muted' => false,
        'display_name' => 'u_testuser',
        'header_img' => null,
        'title' => '',
        'coins' => 0,
        'previous_names' => [],
        'over_18' => false,
        'icon_size' => [256, 256],
        'primary_color' => '',
        'icon_img' => 'https://www.redditstatic.com/avatars/defaults/v2/avatar_default_1.png',
        'description' => '',
        'submit_link_label' => '',
        'header_size' => null,
        'restrict_commenting' => false,
        'subscribers' => 0,
        'submit_text_label' => '',
        'is_default_icon' => true,
        'link_flair_position' => '',
        'display_name_prefixed' => 'u/testuser',
        'key_color' => '',
        'name' => 't5_abc123',
        'is_default_banner' => true,
        'url' => '/user/testuser/',
        'quarantine' => false,
        'hide_ads' => false,
        'user_is_moderator' => false,
        'public_description' => '',
        'link_flair_enabled' => false,
        'disable_contributor_requests' => false,
        'subreddit_type' => 'user',
        'user_is_subscriber' => false
    ],
    'pref_show_snoovatar' => true,
    'name' => 'testuser',
    'pref_clickgadget' => 5,
    'created' => 1185235661,
    'created_utc' => 1185235661,
    'gold_creddits' => 0,
    'id' => 'cr44xbqkw',
    'verified' => true,
    'pref_geopopular' => 'GLOBAL',
    'over_18' => false,
    'is_gold' => false,
    'is_mod' => false,
    'awarder_karma' => 0,
    'awardee_karma' => 0,
    'icon_img' => 'https://www.redditstatic.com/avatars/defaults/v2/avatar_default_1.png',
    'hide_from_robots' => false,
    'link_karma' => 1024,
    'comment_karma' => 4096,
    'total_karma' => 5120,
    'is_suspended' => false,
    'pref_video_autoplay' => true,
    'has_verified_email' => true,
    'pref_nightmode' => true,
    'pref_no_profanity' => false,
    'has_external_account' => false,
    'pref_geopopular' => '',
    'pref_show_trending' => false,
    'pref_show_presence' => true,
    'pref_email_messages' => false,
    'features' => [
        'modmail_harassment_filter' => true,
        'mod_service_mute_writes' => true,
        'promoted_trend_blanks' => true,
        'show_amp_link' => true,
        'mweb_in_feed_refresh' => [
            'owner' => 'growth',
            'variant' => 'control_2',
            'experiment_id' => 507
        ],
        'is_email_permission_required' => true,
        'mod_awards' => true,
        'mweb_xpromo_revamp_v3' => [
            'owner' => 'growth',
            'variant' => 'treatment_2',
            'experiment_id' => 480
        ],
        'chat_subreddit' => true,
        'awards_on_streams' => true,
        'mweb_xpromo_modal_listing_click_daily_dismissible_ios' => true,
        'modlog_copyright_removal' => true,
        'do_not_track' => true,
        'images_in_comments' => true,
        'mod_service_mute_reads' => true,
        'chat_user_settings' => true,
        'use_pref_account_deployment' => true,
        'mweb_xpromo_interstitial_comments_ios' => true,
        'mweb_xpromo_modal_listing_click_daily_dismissible_android' => true,
        'premium_subscriptions_table' => true,
        'mweb_xpromo_interstitial_comments_android' => true,
        'crowd_control_for_post' => true,
        'mweb_nsfw_xpromo' => [
            'owner' => 'growth',
            'variant' => 'control_1',
            'experiment_id' => 361
        ],
        'mweb_footer_upsell' => [
            'owner' => 'growth',
            'variant' => 'truncate_posts',
            'experiment_id' => 497
        ],
        'chat_group_rollout' => true,
        'resized_styles_images' => true,
        'noreferrer_to_noopener' => true,
        'swap_steps_two_and_three_recalibration' => [
            'owner' => 'growth',
            'variant' => 'treatment_4',
            'experiment_id' => 324
        ],
        'expensive_coins_package' => true
    ]
];

echo json_encode($data);